const fs = require('fs');
const jsonFormat = require('json-format');
const FISH = require('./fish.json');
const cheerio = require('cheerio');
const fetch = require('node-fetch');
const Axios = require('axios');

const URL = 'https://nookipedia.com/wiki/File:{{BUG_NAME}}_HHD_Icon.png';
const JSON_CONFIG = {
	type : 'space',
	size : 4
};

const rawData = [
    {
      "Check": "",
      "BUG": "Common Butterfly",
      "PRICE": 90,
      "PLACE": "Air",
      "J": 0,
      "F": 0,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 0,
      "A__1": 0,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Mosquito",
      "PRICE": 130,
      "PLACE": "Air",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Darner Dragonfly",
      "PRICE": 200,
      "PLACE": "Air",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Agrias Butterfly",
      "PRICE": 3000,
      "PLACE": "Air",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Moth",
      "PRICE": 60,
      "PLACE": "Air (Near Lights)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Firefly",
      "PRICE": 300,
      "PLACE": "Air (Near Water)",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 2,
      "J__2": 0,
      "A__1": 0,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Raja Brooke Butterfly",
      "PRICE": 2500,
      "PLACE": "Air (Near Water)",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Wharf Roach",
      "PRICE": 200,
      "PLACE": "Beach",
      "J": 2,
      "F": 2,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Yellow Butterfly",
      "PRICE": 90,
      "PLACE": "Flowers",
      "J": 0,
      "F": 0,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 0,
      "A__1": 0,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Honeybee",
      "PRICE": 100,
      "PLACE": "Flowers",
      "J": 0,
      "F": 0,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 0,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Ladybug",
      "PRICE": 200,
      "PLACE": "Flowers",
      "J": 0,
      "F": 0,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 0,
      "A__1": 0,
      "S": 0,
      "O": 2,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Mantis",
      "PRICE": 430,
      "PLACE": "Flowers",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 2,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Emperor Butterfly",
      "PRICE": 2500,
      "PLACE": "Flowers",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Birdwing Butterfly",
      "PRICE": 4000,
      "PLACE": "Flowers",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "6p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Peacock Butterfly",
      "PRICE": 220,
      "PLACE": "Flowers (Blue/Black/Purple)",
      "J": 1,
      "F": 1,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Tiger Butterfly",
      "PRICE": 160,
      "PLACE": "Flowers (Red)",
      "J": 1,
      "F": 1,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Orchid Mantis",
      "PRICE": 2400,
      "PLACE": "Flowers (White)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Long Locust",
      "PRICE": 200,
      "PLACE": "Ground",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Tiger Beetle",
      "PRICE": 1500,
      "PLACE": "Ground",
      "J": 1,
      "F": 1,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": "4p",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Tarantula",
      "PRICE": 8000,
      "PLACE": "Ground",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Pill Bug",
      "PRICE": 250,
      "PLACE": "Hit Rocks",
      "J": 2,
      "F": 2,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Pond Skater",
      "PRICE": 130,
      "PLACE": "Ponds",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Diving Beetle",
      "PRICE": 800,
      "PLACE": "River",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Snail",
      "PRICE": 250,
      "PLACE": "Shrubs (Rain)",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "11p",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Violin Beetle",
      "PRICE": 260,
      "PLACE": "Stumps",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Fly",
      "PRICE": 60,
      "PLACE": "Trash",
      "J": 2,
      "F": 2,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Ant",
      "PRICE": 80,
      "PLACE": "Trash",
      "J": 2,
      "F": 2,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Stink Bug",
      "PRICE": 120,
      "PLACE": "Trees",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Oak Silk Moth",
      "PRICE": 1200,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Horned Dynastid",
      "PRICE": 1350,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Lantern Fly",
      "PRICE": 1800,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Rainbow Stag",
      "PRICE": 10000,
      "PLACE": "Trees",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Goliath Beetle",
      "PRICE": 6000,
      "PLACE": "Trees (Palm)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 2,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Horned Atlas",
      "PRICE": 8000,
      "PLACE": "Trees (Palm)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Spider",
      "PRICE": 300,
      "PLACE": "Trees (Shaken)",
      "J": 0,
      "F": 0,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "11p",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Bee",
      "PRICE": 2500,
      "PLACE": "Trees (Shaken)",
      "J": 2,
      "F": 2,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Flea",
      "PRICE": 70,
      "PLACE": "Villagers",
      "J": 0,
      "F": 0,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 2,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Monarch Butterfly",
      "PRICE": 140,
      "PLACE": "Air (Near Flowers)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 1,
      "A__1": 1,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Hermit Crab",
      "PRICE": 1000,
      "PLACE": "Beach (Island)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 1,
      "A__1": 1,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 2,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Grasshopper",
      "PRICE": 160,
      "PLACE": "Ground",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Migratory Locust",
      "PRICE": 600,
      "PLACE": "Ground",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 1,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "11p",
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Longhorn Beetle",
      "PRICE": 260,
      "PLACE": "Stumps",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 2,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Drone Beetle",
      "PRICE": 100,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 2,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Fruit Beetle",
      "PRICE": 100,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Walking Stick",
      "PRICE": 600,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Miyama Stag Beetle",
      "PRICE": 1000,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Saw Stag Beetle",
      "PRICE": 2000,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Jewel Beetle",
      "PRICE": 2400,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Scarab Beetle",
      "PRICE": 6000,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Giant Stag",
      "PRICE": 10000,
      "PLACE": "Trees",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": "July-August",
      "Evening (4p-7p)": "July-August",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "July-August"
    },
    {
      "Check": "",
      "BUG": "Horned Elephant",
      "PRICE": 8000,
      "PLACE": "Trees (Palm)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Cyclommatus Stag",
      "PRICE": 8000,
      "PLACE": "Trees (Palm)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Golden Stag",
      "PRICE": 12000,
      "PLACE": "Trees (Palm)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Horned Hercules",
      "PRICE": 12000,
      "PLACE": "Trees (Palm)",
      "J": 1,
      "F": 1,
      "M": 1,
      "A": 1,
      "M__1": 1,
      "J__1": 1,
      "J__2": 2,
      "A__1": 2,
      "S": 1,
      "O": 1,
      "N": 1,
      "D": 1,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Red Dragonfly",
      "PRICE": 80,
      "PLACE": "Air",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 0,
      "A__1": 0,
      "S": 2,
      "O": 2,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "11p",
      "Late (4a-9a)": "6a"
    },
    {
      "Check": "",
      "BUG": "Giant Petaltail",
      "PRICE": 8000,
      "PLACE": "Air",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 0,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "11p",
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Banded Dragonfly",
      "PRICE": 4500,
      "PLACE": "Air (Near Water)",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 2,
      "A__1": 2,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Cricket",
      "PRICE": 160,
      "PLACE": "Ground",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 0,
      "A__1": 0,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Locust",
      "PRICE": 400,
      "PLACE": "Ground",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 0,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 2,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Walking Leaf",
      "PRICE": 600,
      "PLACE": "Ground",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Bell Cricket",
      "PRICE": 1720,
      "PLACE": "Ground",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 0,
      "A__1": 0,
      "S": 2,
      "O": 2,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": "",
      "Night (7p-4a)": "",
      "Late (4a-9a)": ""
    },
    {
      "Check": "",
      "BUG": "Scorpion",
      "PRICE": 8000,
      "PLACE": "Ground",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": "",
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "House Centipede",
      "PRICE": 250,
      "PLACE": "Hit Rocks",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 0,
      "A__1": 2,
      "S": 2,
      "O": 2,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Centipede",
      "PRICE": 300,
      "PLACE": "Hit Rocks",
      "J": 2,
      "F": 2,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 1,
      "J__2": 0,
      "A__1": 0,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Dung Beetle",
      "PRICE": 800,
      "PLACE": "Snowballs",
      "J": 2,
      "F": 2,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 0,
      "A__1": 0,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Cicada Shell",
      "PRICE": 100,
      "PLACE": "Trees",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 2,
      "A__1": 2,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Brown Cicada",
      "PRICE": 200,
      "PLACE": "Trees",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 2,
      "A__1": 2,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Robust Cicada",
      "PRICE": 300,
      "PLACE": "Trees",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 2,
      "A__1": 2,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 1,
      "Morning (8a-5p)": "",
      "Evening (4p-7p)": "5p",
      "Night (7p-4a)": 1,
      "Late (4a-9a)": "8a"
    },
    {
      "Check": "",
      "BUG": "Walker Cicada",
      "PRICE": 400,
      "PLACE": "Trees",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 2,
      "A__1": 2,
      "S": 2,
      "O": 0,
      "N": 0,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Giant Cicada",
      "PRICE": 500,
      "PLACE": "Trees",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 2,
      "A__1": 2,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 2,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Evening Cicada",
      "PRICE": 550,
      "PLACE": "Trees",
      "J": 0,
      "F": 0,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 2,
      "A__1": 2,
      "S": 0,
      "O": 0,
      "N": 0,
      "D": 2,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Bagworm",
      "PRICE": 300,
      "PLACE": "Trees (Shaken)",
      "J": 2,
      "F": 2,
      "M": 0,
      "A": 0,
      "M__1": 0,
      "J__1": 0,
      "J__2": 0,
      "A__1": 0,
      "S": 0,
      "O": 2,
      "N": 2,
      "D": 2,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 11,
      "Late (4a-9a)": 1
    },
    {
      "Check": "",
      "BUG": "Mole Cricket",
      "PRICE": 280,
      "PLACE": "Underground",
      "J": 2,
      "F": 2,
      "M": 2,
      "A": 2,
      "M__1": 2,
      "J__1": 0,
      "J__2": 0,
      "A__1": 0,
      "S": 0,
      "O": 0,
      "N": 2,
      "D": 0,
      "Morning (8a-5p)": 1,
      "Evening (4p-7p)": 1,
      "Night (7p-4a)": 1,
      "Late (4a-9a)": 1
    }
  ]

  const MONTH_KEYS = {
    "J": "January",
    "F": "February",
    "M": "March",
    "A": "April",
    "M__1": "May",
    "J__1": "June",
    "J__2": "July",
    "A__1": "August",
    "S": "September",
    "O": "October",
    "N": "November",
    "D": "December",
  }

  const TIME_KEYS = [
    "Morning (8a-5p)",
    "Evening (4p-7p)",
    "Night (7p-4a)",
    "Late (4a-9a)"
  ]

  const downloadFile = async (name) => {
	const pageRes = await fetch(URL.replace('{{BUG_NAME}}', name));
	const pageHtml = await pageRes.text();
	console.log('[Success] Fetched Page For', name);
	const $ = cheerio.load(pageHtml);
	const img = $('#file > a > img').attr('src');
	const imageUrl = `https://nookipedia.com/${img}`;

	await new Promise(async (resolve, reject) => {
		const writer = fs.createWriteStream(`images/bug/${name}.png`);

		const response = await Axios({
			url          : imageUrl,
			method       : 'GET',
			responseType : 'stream'
		});

		console.log('[Success] Fetched Image For', name);

		response.data.pipe(writer);

		return new Promise((resolve, reject) => {
			writer.on('finish', resolve);
			writer.on('error', reject);
		});
	});
};

const dataPromises = rawData.map((bug) => {
    const Months = Object.keys(MONTH_KEYS).filter(m => bug[m] !== 0).map(m => MONTH_KEYS[m]);
    const Times = TIME_KEYS.filter(t => bug[t] !== "");

    const Bug = {
        Name: bug.BUG,
        Price: bug.PRICE,
        Location: bug.PLACE,
        Months,
        Times,
    };

    return Bug;
})

fs.writeFileSync('bug.json', jsonFormat(dataPromises, JSON_CONFIG));

console.log('[done]');